# Generated by Django 5.1 on 2024-10-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('displayname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('work_phone', models.CharField(max_length=12)),
                ('emergency_phone', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
