# Generated by Django 5.1 on 2024-10-13 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_supply', models.CharField(blank=True, max_length=30, null=True)),
                ('estimate_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('sales_person', models.CharField(blank=True, max_length=30, null=True)),
                ('project_name', models.CharField(blank=True, max_length=30, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('shipping', models.IntegerField(blank=True, null=True)),
                ('adjustments', models.IntegerField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
