# Generated by Django 5.1 on 2024-10-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_estimates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estimates',
        ),
    ]
