# Generated by Django 5.1 on 2024-09-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.TextField()),
                ('street_address', models.TextField()),
                ('city', models.TextField()),
            ],
        ),
    ]
