# Generated by Django 5.1 on 2024-09-01 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0004_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='profile',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
