# Generated by Django 5.1 on 2024-09-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0006_useraddress_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
