# Generated by Django 5.1 on 2024-09-09 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0007_useraddress_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='company',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=10, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('balance', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krupa.orders')),
            ],
        ),
    ]
