# Generated by Django 5.1 on 2024-10-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0010_category_category_image_category_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
