# Generated by Django 5.1 on 2024-10-16 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_estimates'),
        ('krupa', '0012_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.managers'),
        ),
    ]
