# Generated by Django 5.1 on 2024-10-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0021_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
