# Generated by Django 5.1 on 2024-10-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0023_estimate_created_date_invoiceestimate_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
