# Generated by Django 5.1 on 2024-11-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0026_salesorder_satus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='satus',
            field=models.CharField(blank=True, default='SENT', max_length=30, null=True),
        ),
    ]
