# Generated by Django 5.1 on 2024-11-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0027_alter_salesorder_satus'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceestimate',
            name='status',
            field=models.CharField(blank=True, default='PENDING', max_length=30, null=True),
        ),
    ]
