# Generated by Django 5.1 on 2024-11-03 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0030_companyinfo_company_name_alter_companyinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceestimate',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='krupa.estimate'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='krupa.estimate'),
        ),
    ]
