# Generated by Django 5.1 on 2024-11-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0031_invoiceestimate_estimate_salesorder_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('companyname', models.CharField(blank=True, max_length=200, null=True)),
                ('vendoremail', models.EmailField(blank=True, max_length=254, null=True)),
                ('vendorphone1', models.CharField(blank=True, max_length=15, null=True)),
                ('vendorphone2', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_Treatment', models.CharField(blank=True, max_length=50, null=True)),
                ('sourceofsupply', models.CharField(blank=True, max_length=100, null=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('openingbalance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('paymentterms', models.CharField(blank=True, max_length=100, null=True)),
                ('pricelist', models.CharField(blank=True, max_length=100, null=True)),
                ('enableportal', models.BooleanField(blank=True, default=False, null=True)),
                ('portallanguage', models.CharField(blank=True, max_length=50, null=True)),
                ('documents', models.TextField(blank=True, null=True)),
                ('billingattention', models.CharField(blank=True, max_length=200, null=True)),
                ('billingcountry', models.CharField(blank=True, max_length=100, null=True)),
                ('billingaddress1', models.TextField(blank=True, null=True)),
                ('billingaddress2', models.TextField(blank=True, null=True)),
                ('billingcity', models.CharField(blank=True, max_length=100, null=True)),
                ('billingstate', models.CharField(blank=True, max_length=100, null=True)),
                ('billingpincode', models.CharField(blank=True, max_length=10, null=True)),
                ('billingphone', models.CharField(blank=True, max_length=15, null=True)),
                ('shippingattention', models.CharField(blank=True, max_length=200, null=True)),
                ('shippingcountry', models.CharField(blank=True, max_length=100, null=True)),
                ('shippingaddress1', models.TextField(blank=True, null=True)),
                ('shippingaddress2', models.TextField(blank=True, null=True)),
                ('shippingcity', models.CharField(blank=True, max_length=100, null=True)),
                ('shippingstate', models.CharField(blank=True, max_length=100, null=True)),
                ('shippingpincode', models.CharField(blank=True, max_length=10, null=True)),
                ('shippingphone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
