# Generated by Django 5.1 on 2024-11-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0034_alter_purchaseitem_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bill_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='due_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
