# Generated by Django 5.1 on 2024-11-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0035_alter_purchase_bill_date_alter_purchase_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='bill_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='due_date',
            new_name='expected_delivery_date',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='bill',
            new_name='purchase_order',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='order_number',
            new_name='reference',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='shipping_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
