# Generated by Django 5.1 on 2024-11-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0036_rename_bill_date_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(blank=True, default='PENDING', max_length=30, null=True),
        ),
    ]
