# Generated by Django 5.1 on 2024-11-06 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0039_bill_billitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='vendor_name',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='krupa.vendor'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vendor_name',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='krupa.vendor'),
        ),
    ]
